services:
  portal-auth-center:
    container_name: portal-auth-center
    restart: always
    image: dev.chuyuwater.cn:32003/dev/auth-center:latest
    ports:
      - "20001:8080"
    entrypoint: [ "java" ]
    command: [
      "-XX:InitialRAMPercentage=75.0",
      "-XX:MaxRAMPercentage=75.0",
      "-jar",
      "/app/app.jar"
    ]
    mem_limit: 2g
    mem_reservation: 1g
    stop_grace_period: 60s
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s