spring:
  application:
    name: portal-auth-center
---
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848
        username: dev
        password: 7rPBGRZ0aGnXUmtA
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:18848
        username: dev
        password: 7rPBGRZ0aGnXUmtA
        file-extension: yml
        namespace: public
        group: DEFAULT_GROUP

  config:
    import:
      - nacos:${spring.application.name}.yml