logging:
  level:
    root: debug
    com.alibaba.nacos: off
    org.springframework.kafka: info

server:
  port: 20001

spring:
  cache:
    type: redis
  data:
    redis:
      password: chuyu@redis123
      timeout: 5s
      cluster:
        nodes: 127.0.0.1:6379, 127.0.0.1:6380, 127.0.0.1:6381
        max-redirects: 3
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      # 这里的数量*实例数=分区数
      concurrency: 3
      type: batch
      ack-mode: manual_immediate

  datasource:
    username: dev
    password: 9fVBpXJqRaFY
    #    url: jdbc:oceanbase://localhost:2881/portal_auth_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    #    driver-class-name: com.oceanbase.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal_auth_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&timezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 4
      max-active: 20
      min-idle: 4
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 600000
      test-on-borrow: false
      test-on-return: false
      remove-abandoned: false
      test-while-idle: true
      validation-query: SELECT
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,slf4j
      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            multi-statement-allow: true

oss:
  access-key: aWhBryDoYGVXxviqNT15
  secret-key: 2yrDkt5N7WcHLvpYdXT3940mOCgsIbqwhQa1uolS
  bucket-name: digital
  endpoint: http://127.0.0.1:19000
  custom-domain: https://dev.chuyuwater.cn:32008

oa:
  url: http://www.chuyuwater.cn:8088
  app-id: ChuyuPortalDev
  secret: 39472554-4513-46e8-9910-d64de60549b1
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0bDrmazR/mUgufJOjAD6h4SZbG5n98yxAsF33GvAC41LB3/hFeUU5x1Xqhgzjh5HEprvhO09z19T6H1Avl6akkIU/h7AqnBWdLxprOCUHAEqZJ2Rh1mfWb9l1xWJdHT2ZVe3A3B4YHajJYdiEWPqGEZrrhw7YuhvL9j8lyNBC+JdXi0pkxMInfadMueb9Vu6tNMJc6XF6RmPcFDhPfOlCeXFnCtNUwBKQUfbOkT6wLeBYrMl/fAbNTW7HPJzK1G25wMTgUZmnHnXnP5TFt9/nKf05mO6BqSM4TpmefQBt7E6aGecyuQyrmqxX7UxNgAUepuSkjHGDLiMB/K1rTQLswIDAQAB"
