logging:
  level:
    root: debug
    com.alibaba.nacos: off
    org.springframework.kafka: info

server:
  port: 20001

spring:
  cache:
    type: redis
  data:
    redis:
      password: chuyu@redis123
      timeout: 5s
      cluster:
        nodes: 127.0.0.1:6379, 127.0.0.1:6380, 127.0.0.1:6381
        max-redirects: 3
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      # 这里的数量*实例数=分区数
      concurrency: 3
      type: batch
      ack-mode: manual_immediate

  datasource:
    username: dev
    password: 9fVBpXJqRaFY
    #    url: jdbc:oceanbase://localhost:2881/portal_auth_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    #    driver-class-name: com.oceanbase.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal_auth_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&timezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 4
      max-active: 20
      min-idle: 4
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 600000
      test-on-borrow: false
      test-on-return: false
      remove-abandoned: false
      test-while-idle: true
      validation-query: SELECT
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,slf4j
      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            multi-statement-allow: true

mybatis-plus:
  configuration:
    cache-enabled: false
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: false
    #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleteTime
      logic-delete-value: 1
      logic-not-delete-value: 0

  mapper-locations: classpath*:com/hbcy/**/mapper/*.xml
  type-handlers-package: com.hbcy.common.db.typehandler
oss:
  access-key: aWhBryDoYGVXxviqNT15
  secret-key: 2yrDkt5N7WcHLvpYdXT3940mOCgsIbqwhQa1uolS
  bucket-name: digital
  endpoint: http://127.0.0.1:19000
  custom-domain: https://dev.chuyuwater.cn:32008

sa-token:
  token-name: "x-auth-token"
  is-print: off
  is-read-header: true
  is-read-cookie: false
  is-log: false
  token-style: simple-uuid