<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hbcy.authcenter</groupId>
        <artifactId>authcenter</artifactId>
        <version>1.0.1</version>
    </parent>

    <artifactId>cloud-sdk</artifactId>
    <version>1.0.3-SNAPTSHOT</version>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.hbcy.authcenter</groupId>
            <artifactId>sdk</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>com.hbcy.common</groupId>
            <artifactId>webdb</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.hbcy.common</groupId>
            <artifactId>redis</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

</project>